services:
  - type: web
    name: dromo-import-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: DROMO_LICENSE_KEY
        sync: false
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: DROMO_SCHEMA_ID
        sync: false